export type QuestionType =
  | "single"
  | "multiple"
  | "text"
  | "number"
  | "scale";

export type Question = {
  id: string;
  number: number;
  section: string;
  label: string;
  type: QuestionType;
  required?: boolean;
  options?: string[];
  min?: number;
  max?: number;
  otherField?: string;
};

export const QUESTIONNAIRE_SECTIONS = [
  {
    id: "A",
    title: "Sección A: Datos generales del docente",
  },
  {
    id: "B",
    title: "Sección B: Información del curso",
  },
  {
    id: "C",
    title: "Sección C: Diseño y evaluación del curso",
  },
  {
    id: "D",
    title: "Sección D: Datos complementarios del esfuerzo",
  },
  {
    id: "E",
    title: "Sección E: Factores contextuales y percepciones",
  },
];

export const QUESTIONNAIRE_SCHEMA: Question[] = [
  {
    id: "q01_rango_edad",
    number: 1,
    section: "A",
    label: "Rango de edad",
    type: "single",
    required: true,
    options: [
      "Entre 20 y 25",
      "Entre 26 y 30",
      "Entre 31 y 35",
      "Entre 36 y 40",
      "Entre 41 y 45",
      "Entre 46 y 50",
      "Entre 51 y 55",
      "Entre 56 y 60",
      "Entre 61 y 65",
      "Más de 65",
    ],
  },
  {
    id: "q02_genero",
    number: 2,
    section: "A",
    label: "Género",
    type: "single",
    required: true,
    options: ["Femenino", "Masculino", "No binario", "Prefiere no decir"],
  },
  {
    id: "q03_nivel_academico",
    number: 3,
    section: "A",
    label: "Nivel académico más alto alcanzado",
    type: "single",
    required: true,
    options: ["Profesional", "Especialización", "Maestría", "Doctorado", "Otro"],
    otherField: "q03_nivel_academico_otro",
  },
  {
    id: "q04_area_formacion_pregrado",
    number: 4,
    section: "A",
    label: "Área de formación en pregrado",
    type: "single",
    required: true,
    options: [
      "Agronomía, Veterinaria y afines",
      "Bellas Artes",
      "Ciencias de la Educación",
      "Ciencias de la Salud",
      "Ciencias Sociales y Humanas",
      "Economía, Administración, Contaduría y afines",
      "Ingeniería, Arquitectura, Urbanismo y afines",
      "Matemáticas y Ciencias Naturales",
    ],
  },
  {
    id: "q05_area_desempeno_actual",
    number: 5,
    section: "A",
    label: "Área de desempeño principal actual",
    type: "single",
    required: true,
    options: [
      "Agronomía, Veterinaria y afines",
      "Artes y Diseño",
      "Ciencias de la Educación",
      "Ciencias de la Salud",
      "Ciencias Sociales y Humanas",
      "Economía, Administración, Contaduría y afines",
      "Ingeniería, Arquitectura, Urbanismo y afines",
      "Matemáticas y Ciencias Naturales",
      "Otro",
    ],
    otherField: "q05_area_desempeno_actual_otro",
  },
  {
    id: "q06_anios_experiencia_docente",
    number: 6,
    section: "A",
    label: "Años de experiencia docente total",
    type: "number",
    required: true,
    min: 0,
  },
  {
    id: "q07_anios_experiencia_online",
    number: 7,
    section: "A",
    label: "Años de experiencia diseñando u orientando cursos en línea",
    type: "number",
    required: true,
    min: 0,
  },
  {
    id: "q08_competencias_digitales",
    number: 8,
    section: "A",
    label: "Nivel de competencias digitales o TIC",
    type: "scale",
    required: true,
    min: 1,
    max: 5,
  },

  {
    id: "q09_institucion",
    number: 9,
    section: "B",
    label: "Institución",
    type: "text",
  },
  {
    id: "q10_tipo_institucion",
    number: 10,
    section: "B",
    label: "Tipo de institución",
    type: "single",
    required: true,
    options: ["Pública", "Privada", "Mixta", "Otro"],
    otherField: "q10_tipo_institucion_otro",
  },
  {
    id: "q11_nombre_curso",
    number: 11,
    section: "B",
    label: "Nombre del curso",
    type: "text",
  },
  {
    id: "q12_programa_academico",
    number: 12,
    section: "B",
    label: "Nombre del programa académico",
    type: "text",
  },
  {
    id: "q13_correo_resultados",
    number: 13,
    section: "B",
    label:
      "Correo electrónico para conocer los resultados finales de la investigación",
    type: "text",
  },
  {
    id: "q14_nivel_academico_curso",
    number: 14,
    section: "B",
    label: "Nivel académico del curso",
    type: "single",
    required: true,
    options: ["Pregrado", "Posgrado", "Formación continua", "Otro"],
    otherField: "q14_nivel_academico_curso_otro",
  },
  {
    id: "q15_area_disciplinar",
    number: 15,
    section: "B",
    label: "Área disciplinar principal",
    type: "single",
    required: true,
    options: [
      "Agronomía, Veterinaria y afines",
      "Artes y Diseño",
      "Ciencias de la Educación",
      "Ciencias de la Salud",
      "Ciencias Sociales y Humanas",
      "Economía, Administración, Contaduría y afines",
      "Ingeniería, Arquitectura, Urbanismo y afines",
      "Matemáticas y Ciencias Naturales",
      "Otro",
    ],
    otherField: "q15_area_disciplinar_otro",
  },
  {
    id: "q16_duracion_curso_semanas",
    number: 16,
    section: "B",
    label: "Duración del curso en semanas",
    type: "number",
    required: true,
    min: 1,
  },
  {
    id: "q17_numero_estudiantes",
    number: 17,
    section: "B",
    label: "Número promedio de estudiantes",
    type: "number",
    required: true,
    min: 0,
  },
  {
    id: "q18_modalidad_curso",
    number: 18,
    section: "B",
    label: "Modalidad del curso",
    type: "single",
    required: true,
    options: [
      "Totalmente en línea (asíncrono)",
      "En línea con sesiones síncronas",
      "Híbrido (presencial + virtual)",
      "Otro",
    ],
    otherField: "q18_modalidad_curso_otro",
  },
  {
    id: "q19_tipo_curso_ofrecido",
    number: 19,
    section: "B",
    label: "Tipo de curso ofrecido por usted",
    type: "single",
    required: true,
    options: [
      "Nuevo (diseño desde cero)",
      "Adaptación o rediseño parcial",
      "Reutilización sin cambios",
      "Otro",
    ],
    otherField: "q19_tipo_curso_ofrecido_otro",
  },
  {
    id: "q20_porcentaje_contenido_nuevo",
    number: 20,
    section: "B",
    label: "Porcentaje de contenido nuevo creado para el curso",
    type: "number",
    required: true,
    min: 0,
    max: 100,
  },
  {
    id: "q21_plataforma_lms",
    number: 21,
    section: "B",
    label: "Plataforma principal utilizada",
    type: "single",
    required: true,
    options: ["Moodle", "Canvas", "Blackboard", "Google Classroom", "Open edX", "Otra"],
    otherField: "q21_plataforma_lms_otra",
  },
  {
    id: "q22_numero_modulos",
    number: 22,
    section: "B",
    label: "Número total de módulos o unidades del curso",
    type: "number",
    required: true,
    min: 0,
  },

  {
    id: "q23_tipo_curso",
    number: 23,
    section: "C",
    label: "Tipo de curso",
    type: "single",
    required: true,
    options: ["Teórico", "Teórico-práctico", "Práctico", "Otro"],
    otherField: "q23_tipo_curso_otro",
  },
  {
    id: "q24_metodologia_principal",
    number: 24,
    section: "C",
    label: "Metodología principal utilizada",
    type: "multiple",
    required: true,
    options: [
      "Expositiva",
      "Basada en problemas",
      "Basada en proyectos",
      "Basada en competencias",
      "Aprendizaje activo / Colaborativo",
      "Otra",
    ],
    otherField: "q24_metodologia_principal_otra_texto",
  },
  {
    id: "q25_numero_actividades_evaluadas",
    number: 25,
    section: "C",
    label:
      "Número total aproximado de actividades evaluadas (tareas, quizzes, proyectos)",
    type: "number",
    required: true,
    min: 0,
  },
  {
    id: "q26_porcentaje_correccion_manual",
    number: 26,
    section: "C",
    label:
      "Porcentaje de evaluaciones con corrección manual (ensayos, proyectos, foros)",
    type: "number",
    required: true,
    min: 0,
    max: 100,
  },
  {
    id: "q27_herramientas_automaticas_evaluacion",
    number: 27,
    section: "C",
    label: "Uso de herramientas automáticas de evaluación",
    type: "single",
    required: true,
    options: ["Sí", "No", "Parcialmente"],
  },
  {
    id: "q28_complejidad_multimedia",
    number: 28,
    section: "C",
    label: "Complejidad multimedia del curso",
    type: "scale",
    required: true,
    min: 1,
    max: 5,
  },
  {
    id: "q29_porcentaje_recursos_autor",
    number: 29,
    section: "C",
    label:
      "Porcentaje de recursos creados con herramientas de autor o edición",
    type: "number",
    required: true,
    min: 0,
    max: 100,
  },

  {
    id: "q35_numero_asistentes",
    number: 35,
    section: "D",
    label:
      "Número de asistentes o ayudantes del curso, escriba 0 si no contó con ellos",
    type: "number",
    required: true,
    min: 0,
  },

  {
    id: "q36_infraestructura_adecuada",
    number: 36,
    section: "E",
    label:
      "¿Tuvo acceso a infraestructura tecnológica adecuada para orientar su curso en línea?",
    type: "single",
    required: true,
    options: ["Sí", "No"],
  },
  {
    id: "q37_apoyo_tecnico_institucional",
    number: 37,
    section: "E",
    label: "El apoyo técnico o institucional recibido fue",
    type: "scale",
    required: true,
    min: 1,
    max: 5,
  },
  {
    id: "q38_complejidad_contenido",
    number: 38,
    section: "E",
    label: "La complejidad percibida del contenido del curso fue",
    type: "scale",
    required: true,
    min: 1,
    max: 5,
  },
  {
    id: "q39_esfuerzo_percibido",
    number: 39,
    section: "E",
    label: "El nivel de esfuerzo docente percibido para este curso es",
    type: "scale",
    required: true,
    min: 1,
    max: 5,
  },
  {
    id: "q40_satisfaccion_resultados",
    number: 40,
    section: "E",
    label:
      "La satisfacción con los resultados del curso (aprendizaje de los estudiantes) es",
    type: "scale",
    required: true,
    min: 1,
    max: 5,
  },
  {
    id: "q41_factores_aumentaron_esfuerzo",
    number: 41,
    section: "E",
    label: "Factores que más aumentaron su esfuerzo docente (seleccione máximo 3 opciones)",
    type: "multiple",
    required: true,
    options: [
      "Tamaño del grupo de estudiantes",
      "Complejidad del contenido",
      "Falta de apoyo técnico",
      "Creación de material multimedia",
      "Evaluaciones manuales",
      "Baja conectividad de los estudiantes",
      "Otros",
    ],
    otherField: "q41_factores_aumentaron_esfuerzo_otros_texto",
  },
  {
    id: "q42_uso_ia_generativa",
    number: 42,
    section: "E",
    label: "Uso de herramientas de inteligencia artificial generativa",
    type: "multiple",
    required: true,
    options: [
      "Diseño curricular",
      "Generación de contenidos educativos",
      "Tener ideas para actividades de aprendizaje",
      "Para crear cuestionarios y exámenes",
      "Para la evaluación",
      "Para la comunicación y la realimentación",
      "Otro",
      "No usé herramientas de inteligencia artificial generativa",
    ],
    otherField: "q42_uso_ia_generativa_otro_texto",
  },
  {
    id: "q43_apoyos_futuros",
    number: 43,
    section: "E",
    label:
      "¿Qué apoyos o recursos reducirían su carga de trabajo en el futuro en este tipo de cursos?",
    type: "text",
  },
];